name: Run Discord Bot

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet d'exécuter manuellement le workflow

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          echo "Google Chrome and ChromeDriver installed"

      - name: Run the bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          TIKTOK_USERNAME: ${{ secrets.TIKTOK_USERNAME }}
        run: |
          python main.py
